# Generated by Django 4.2.26 on 2025-12-08 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parcels', '0003_alter_crop_options_alter_parcel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('type', models.CharField(choices=[('SIEMBRA', 'Siembra'), ('COSECHA', 'Cosecha'), ('CAPACITACION', 'Capacitación'), ('REUNION', 'Reunión'), ('INSPECCION', 'Inspección'), ('MANTENIMIENTO', 'Mantenimiento'), ('APLICACION', 'Aplicación de Insumos'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('start_datetime', models.DateTimeField(verbose_name='Fecha y hora de inicio')),
                ('end_datetime', models.DateTimeField(verbose_name='Fecha y hora de fin')),
                ('all_day', models.BooleanField(default=False, verbose_name='Todo el día')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=10, verbose_name='Prioridad')),
                ('completed', models.BooleanField(default=False, verbose_name='Completado')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Recordatorio enviado')),
                ('reminder_minutes', models.IntegerField(default=60, verbose_name='Minutos antes del recordatorio')),
                ('color', models.CharField(default='#3b82f6', help_text='Color en formato hexadecimal (ej: #3b82f6)', max_length=7, verbose_name='Color')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización')),
                ('parcels', models.ManyToManyField(blank=True, related_name='events', to='parcels.parcel', verbose_name='Parcelas')),
                ('participants', models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Participantes')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'events_event',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado en')),
                ('method', models.CharField(choices=[('EMAIL', 'Email'), ('NOTIFICATION', 'Notificación'), ('SMS', 'SMS')], default='NOTIFICATION', max_length=20, verbose_name='Método')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='events.event', verbose_name='Evento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'db_table': 'events_reminder',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_datetime', 'end_datetime'], name='events_even_start_d_e338a8_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['type', 'start_datetime'], name='events_even_type_9261f8_idx'),
        ),
    ]
