# Generated by Django 5.0.1 on 2025-11-21 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('farm_activities', '0001_initial'),
        ('inventory', '0001_initial'),
        ('parcels', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelTraceability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traceability_code', models.CharField(max_length=100, unique=True, verbose_name='Código de trazabilidad')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('total_activities', models.IntegerField(default=0)),
                ('total_inputs_used', models.IntegerField(default=0)),
                ('total_production', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traceability_records', to='campaigns.campaign')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traceability_records', to='parcels.parcel')),
            ],
            options={
                'verbose_name': 'Trazabilidad de Parcela',
                'verbose_name_plural': 'Trazabilidad de Parcelas',
                'db_table': 'parcel_traceability',
                'unique_together': {('parcel', 'campaign')},
            },
        ),
        migrations.CreateModel(
            name='InputUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField()),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('application_method', models.CharField(blank=True, max_length=200)),
                ('purpose', models.CharField(max_length=200)),
                ('weather_conditions', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('farm_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm_activities.farmactivity')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('traceability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_records', to='traceability.parceltraceability')),
            ],
            options={
                'verbose_name': 'Registro de Uso de Insumo',
                'verbose_name_plural': 'Registros de Uso de Insumos',
                'db_table': 'input_usage_records',
                'ordering': ['-application_date'],
            },
        ),
    ]
