# Generated by Django 4.2.26 on 2025-11-26 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('traceability', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parceltraceability',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='parceltraceability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inputusagerecord',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parceltraceability',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parceltraceability',
            name='traceability_code',
            field=models.CharField(max_length=100, verbose_name='Código de trazabilidad'),
        ),
        migrations.AlterUniqueTogether(
            name='parceltraceability',
            unique_together={('organization', 'traceability_code')},
        ),
        migrations.AlterModelTable(
            name='parceltraceability',
            table=None,
        ),
    ]
