# Generated by Django 4.2.26 on 2025-12-08 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('type', models.CharField(choices=[('PRODUCTION', 'Producción'), ('SALES', 'Ventas'), ('QUALITY', 'Calidad'), ('EFFICIENCY', 'Eficiencia'), ('PARTNERS', 'Socios'), ('SURFACE', 'Superficie'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor objetivo')),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor actual')),
                ('unit', models.CharField(help_text='Ej: kg, Bs, %, unidades', max_length=50, verbose_name='Unidad')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'No iniciada'), ('IN_PROGRESS', 'En progreso'), ('AT_RISK', 'En riesgo'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='NOT_STARTED', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'db_table': 'goals_goal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('target_date', models.DateField(verbose_name='Fecha objetivo')),
                ('completed', models.BooleanField(default=False, verbose_name='Completado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado en')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='goals.goal', verbose_name='Meta')),
            ],
            options={
                'verbose_name': 'Hito',
                'verbose_name_plural': 'Hitos',
                'db_table': 'goals_milestone',
                'ordering': ['target_date'],
            },
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['type', 'status'], name='goals_goal_type_f6e7f9_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['start_date', 'end_date'], name='goals_goal_start_d_825b5c_idx'),
        ),
    ]
