# Generated by Django 4.2.26 on 2025-11-26 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=50)),
                ('alert_type', models.CharField(choices=[('HIGH', 'Precio Alto'), ('LOW', 'Precio Bajo'), ('OPPORTUNITY', 'Oportunidad')], max_length=20)),
                ('message', models.TextField()),
                ('percentage_change', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Alerta de Precio',
                'verbose_name_plural': 'Alertas de Precio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('QUINUA', 'Quinua'), ('PAPA', 'Papa'), ('MAIZ', 'Maíz'), ('TRIGO', 'Trigo'), ('CEBADA', 'Cebada'), ('HABA', 'Haba'), ('ARVEJA', 'Arveja')], max_length=50)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('source', models.CharField(default='Sistema Interno', max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Precio de Mercado',
                'verbose_name_plural': 'Precios de Mercado',
                'ordering': ['-date'],
            },
        ),
    ]
