# Generated by Django 5.0.1 on 2025-11-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('demand_level', models.CharField(choices=[('HIGH', 'Alta'), ('MEDIUM', 'Media'), ('LOW', 'Baja')], max_length=20)),
                ('demand_index', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trend_direction', models.CharField(choices=[('INCREASING', 'Aumentando'), ('STABLE', 'Estable'), ('DECREASING', 'Disminuyendo')], max_length=20)),
                ('seasonal_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('market_factors', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tendencia de Demanda',
                'verbose_name_plural': 'Tendencias de Demanda',
                'db_table': 'demand_trends',
                'ordering': ['-date'],
                'unique_together': {('product_name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PriceTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_traded', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('trend_direction', models.CharField(choices=[('UP', 'Subiendo'), ('DOWN', 'Bajando'), ('STABLE', 'Estable')], max_length=20)),
                ('volatility', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('data_source', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tendencia de Precio',
                'verbose_name_plural': 'Tendencias de Precios',
                'db_table': 'price_trends',
                'ordering': ['-date'],
                'unique_together': {('product_name', 'date')},
            },
        ),
    ]
