# Generated by Django 5.0.1 on 2025-11-21 05:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='campaigns.campaign', verbose_name='Campaña')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_price_lists', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Lista de Precios',
                'verbose_name_plural': 'Listas de Precios',
                'db_table': 'price_lists',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio unitario')),
                ('unit_of_measure', models.CharField(max_length=50, verbose_name='Unidad de medida')),
                ('min_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad mínima')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricing.pricelist', verbose_name='Lista de precios')),
            ],
            options={
                'verbose_name': 'Item de Lista de Precios',
                'verbose_name_plural': 'Items de Listas de Precios',
                'db_table': 'price_list_items',
                'ordering': ['product_name'],
            },
        ),
        migrations.AddIndex(
            model_name='pricelist',
            index=models.Index(fields=['code'], name='price_lists_code_64cdf6_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelist',
            index=models.Index(fields=['campaign', 'is_active'], name='price_lists_campaig_7d0894_idx'),
        ),
    ]
