# Generated by Django 4.2.26 on 2025-11-26 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelist',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='pricelist',
            name='price_lists_code_64cdf6_idx',
        ),
        migrations.RemoveIndex(
            model_name='pricelist',
            name='price_lists_campaig_7d0894_idx',
        ),
        migrations.AddField(
            model_name='pricelist',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Código'),
        ),
        migrations.AlterUniqueTogether(
            name='pricelist',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterModelTable(
            name='pricelist',
            table=None,
        ),
    ]
