# Generated by Django 5.0.1 on 2025-11-20 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_partners', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='partner',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner', to=settings.AUTH_USER_MODEL, verbose_name='Usuario asociado'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['ci'], name='partners_ci_68ba63_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['nit'], name='partners_nit_8e3309_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['status'], name='partners_status_6458e3_idx'),
        ),
    ]
