# Generated by Django 4.2.26 on 2025-11-26 02:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('partners', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='partner',
            name='partners_ci_68ba63_idx',
        ),
        migrations.RemoveIndex(
            model_name='partner',
            name='partners_nit_8e3309_idx',
        ),
        migrations.RemoveIndex(
            model_name='partner',
            name='partners_status_6458e3_idx',
        ),
        migrations.AddField(
            model_name='community',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='ci',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El CI debe contener entre 7 y 10 dígitos.', regex='^\\d{7,10}$')], verbose_name='Cédula de Identidad'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='nit',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El NIT debe contener entre 7 y 15 dígitos.', regex='^\\d{7,15}$')], verbose_name='NIT'),
        ),
        migrations.AlterUniqueTogether(
            name='community',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='partner',
            unique_together={('organization', 'ci'), ('organization', 'nit')},
        ),
        migrations.AlterModelTable(
            name='community',
            table=None,
        ),
        migrations.AlterModelTable(
            name='partner',
            table=None,
        ),
    ]
