# Generated by Django 5.0.1 on 2025-11-25 15:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('subdomain', models.CharField(db_index=True, help_text='Subdominio único para acceder: subdominio.tuapp.com', max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='El subdominio solo puede contener letras minúsculas, números y guiones.', regex='^[a-z0-9]([a-z0-9-]*[a-z0-9])?$')], verbose_name='Subdominio')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('plan', models.CharField(choices=[('FREE', 'Gratuito'), ('BASIC', 'Básico'), ('PROFESSIONAL', 'Profesional'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=20, verbose_name='Plan')),
                ('status', models.CharField(choices=[('TRIAL', 'Prueba'), ('ACTIVE', 'Activo'), ('SUSPENDED', 'Suspendido'), ('CANCELLED', 'Cancelado')], default='TRIAL', max_length=20, verbose_name='Estado')),
                ('max_users', models.IntegerField(default=5, verbose_name='Máximo de usuarios')),
                ('max_products', models.IntegerField(default=100, verbose_name='Máximo de productos')),
                ('max_storage_mb', models.IntegerField(default=100, verbose_name='Almacenamiento (MB)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin de prueba')),
                ('subscription_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin de suscripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Configuración')),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
                'db_table': 'tenants_organization',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Propietario'), ('ADMIN', 'Administrador'), ('MEMBER', 'Miembro')], default='MEMBER', max_length=20, verbose_name='Rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tenants.organization', verbose_name='Organización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Miembro de Organización',
                'verbose_name_plural': 'Miembros de Organizaciones',
                'db_table': 'tenants_organization_member',
                'ordering': ['-joined_at'],
                'unique_together': {('organization', 'user')},
            },
        ),
    ]
