# Generated by Django 5.0.1 on 2025-11-20 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_parcels', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='current_crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='parcels.crop', verbose_name='Cultivo actual'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='partners.partner', verbose_name='Socio'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='soil_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to='parcels.soiltype', verbose_name='Tipo de suelo'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['code'], name='parcels_code_882ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['partner'], name='parcels_partner_04d7bc_idx'),
        ),
    ]
