# Generated by Django 4.2.26 on 2025-11-26 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('parcels', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={},
        ),
        migrations.AlterModelOptions(
            name='parcel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='soiltype',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='parcel',
            name='parcels_code_882ecc_idx',
        ),
        migrations.RemoveIndex(
            model_name='parcel',
            name='parcels_partner_04d7bc_idx',
        ),
        migrations.AddField(
            model_name='crop',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcel',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soiltype',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Código de parcela'),
        ),
        migrations.AlterField(
            model_name='soiltype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterUniqueTogether(
            name='crop',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='parcel',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='soiltype',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterModelTable(
            name='crop',
            table=None,
        ),
        migrations.AlterModelTable(
            name='parcel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='soiltype',
            table=None,
        ),
    ]
