# Generated by Django 5.0.1 on 2025-11-21 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('parcels', '0002_initial'),
        ('partners', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PLANTING', 'Recomendación de Siembra'), ('FERTILIZATION', 'Plan de Fertilización'), ('HARVEST', 'Momento Óptimo de Cosecha'), ('MARKET', 'Oportunidad Comercial'), ('PEST_CONTROL', 'Control de Plagas')], max_length=50, unique=True, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Recomendación IA',
                'verbose_name_plural': 'Tipos de Recomendaciones IA',
                'db_table': 'ai_recommendation_types',
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('priority', models.CharField(choices=[('HIGH', 'Alta'), ('MEDIUM', 'Media'), ('LOW', 'Baja')], default='MEDIUM', max_length=20, verbose_name='Prioridad')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nivel de confianza (%)')),
                ('ai_model_version', models.CharField(blank=True, max_length=50, verbose_name='Versión del modelo')),
                ('input_data', models.JSONField(default=dict, verbose_name='Datos de entrada')),
                ('output_data', models.JSONField(default=dict, verbose_name='Datos de salida')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de generación')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válido hasta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('was_applied', models.BooleanField(default=False, verbose_name='Fue aplicada')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aplicación')),
                ('user_rating', models.IntegerField(blank=True, null=True, verbose_name='Calificación (1-5)')),
                ('user_feedback', models.TextField(blank=True, verbose_name='Comentarios del usuario')),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='parcels.parcel', verbose_name='Parcela')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='partners.partner', verbose_name='Socio')),
                ('recommendation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='ai_recommendations.airecommendationtype', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Recomendación IA',
                'verbose_name_plural': 'Recomendaciones IA',
                'db_table': 'ai_recommendations',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AILearningData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_outcome', models.JSONField(default=dict, verbose_name='Resultado real')),
                ('predicted_outcome', models.JSONField(default=dict, verbose_name='Resultado predicho')),
                ('accuracy_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Precisión (%)')),
                ('error_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Margen de error')),
                ('user_satisfaction', models.IntegerField(blank=True, null=True, verbose_name='Satisfacción (1-5)')),
                ('was_successful', models.BooleanField(blank=True, null=True, verbose_name='Fue exitosa')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_data', to='ai_recommendations.airecommendation', verbose_name='Recomendación')),
            ],
            options={
                'verbose_name': 'Dato de Aprendizaje IA',
                'verbose_name_plural': 'Datos de Aprendizaje IA',
                'db_table': 'ai_learning_data',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='FertilizationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=200, verbose_name='Nombre del plan')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
                ('soil_analysis', models.JSONField(default=dict, verbose_name='Análisis de suelo')),
                ('nutrient_deficiencies', models.JSONField(default=list, verbose_name='Deficiencias nutricionales')),
                ('target_yield', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rendimiento objetivo (kg/ha)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fertilization_plans', to='campaigns.campaign', verbose_name='Campaña')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilization_plans', to='parcels.parcel', verbose_name='Parcela')),
                ('recommendation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fertilization_detail', to='ai_recommendations.airecommendation', verbose_name='Recomendación')),
            ],
            options={
                'verbose_name': 'Plan de Fertilización',
                'verbose_name_plural': 'Planes de Fertilización',
                'db_table': 'fertilization_plans',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FertilizationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.IntegerField(verbose_name='Número de aplicación')),
                ('scheduled_date', models.DateField(verbose_name='Fecha programada')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='Fecha real')),
                ('fertilizer_type', models.CharField(max_length=200, verbose_name='Tipo de fertilizante')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad (kg)')),
                ('application_method', models.CharField(max_length=100, verbose_name='Método de aplicación')),
                ('nutrients', models.JSONField(default=dict, verbose_name='Nutrientes (N-P-K)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completada')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='ai_recommendations.fertilizationplan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Aplicación de Fertilización',
                'verbose_name_plural': 'Aplicaciones de Fertilización',
                'db_table': 'fertilization_applications',
                'ordering': ['plan', 'application_number'],
            },
        ),
        migrations.CreateModel(
            name='HarvestRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimal_harvest_date', models.DateField(verbose_name='Fecha óptima de cosecha')),
                ('harvest_window_start', models.DateField(verbose_name='Inicio ventana de cosecha')),
                ('harvest_window_end', models.DateField(verbose_name='Fin ventana de cosecha')),
                ('maturity_level', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nivel de maduración (%)')),
                ('weather_conditions', models.JSONField(default=dict, verbose_name='Condiciones climáticas')),
                ('market_conditions', models.JSONField(default=dict, verbose_name='Condiciones de mercado')),
                ('logistics_readiness', models.CharField(choices=[('READY', 'Listo'), ('PENDING', 'Pendiente'), ('NOT_READY', 'No listo')], max_length=20, verbose_name='Estado logístico')),
                ('storage_availability', models.BooleanField(default=True, verbose_name='Almacenamiento disponible')),
                ('estimated_yield', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rendimiento estimado (kg)')),
                ('estimated_quality', models.CharField(choices=[('PREMIUM', 'Premium'), ('STANDARD', 'Estándar'), ('BASIC', 'Básico')], max_length=20, verbose_name='Calidad estimada')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_recommendations', to='parcels.parcel', verbose_name='Parcela')),
                ('recommendation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_detail', to='ai_recommendations.airecommendation', verbose_name='Recomendación')),
            ],
            options={
                'verbose_name': 'Recomendación de Cosecha',
                'verbose_name_plural': 'Recomendaciones de Cosecha',
                'db_table': 'harvest_recommendations',
            },
        ),
        migrations.CreateModel(
            name='MarketOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Producto')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio actual')),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio predicho')),
                ('price_trend', models.CharField(choices=[('RISING', 'Subiendo'), ('STABLE', 'Estable'), ('FALLING', 'Bajando')], max_length=20, verbose_name='Tendencia de precio')),
                ('demand_level', models.CharField(choices=[('HIGH', 'Alta'), ('MEDIUM', 'Media'), ('LOW', 'Baja')], max_length=20, verbose_name='Nivel de demanda')),
                ('demand_trend', models.CharField(choices=[('INCREASING', 'Aumentando'), ('STABLE', 'Estable'), ('DECREASING', 'Disminuyendo')], max_length=20, verbose_name='Tendencia de demanda')),
                ('market_analysis', models.JSONField(default=dict, verbose_name='Análisis de mercado')),
                ('competitors_data', models.JSONField(default=dict, verbose_name='Datos de competidores')),
                ('action_recommended', models.CharField(choices=[('SELL_NOW', 'Vender Ahora'), ('WAIT', 'Esperar'), ('STORE', 'Almacenar'), ('PROCESS', 'Procesar')], max_length=20, verbose_name='Acción recomendada')),
                ('valid_from', models.DateField(verbose_name='Válido desde')),
                ('valid_until', models.DateField(verbose_name='Válido hasta')),
                ('recommendation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_detail', to='ai_recommendations.airecommendation', verbose_name='Recomendación')),
            ],
            options={
                'verbose_name': 'Oportunidad de Mercado',
                'verbose_name_plural': 'Oportunidades de Mercado',
                'db_table': 'market_opportunities',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='PlantingRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(blank=True, max_length=200, verbose_name='Variedad recomendada')),
                ('optimal_planting_date', models.DateField(verbose_name='Fecha óptima de siembra')),
                ('planting_window_start', models.DateField(verbose_name='Inicio ventana de siembra')),
                ('planting_window_end', models.DateField(verbose_name='Fin ventana de siembra')),
                ('soil_conditions', models.JSONField(default=dict, verbose_name='Condiciones de suelo')),
                ('climate_conditions', models.JSONField(default=dict, verbose_name='Condiciones climáticas')),
                ('market_demand', models.CharField(choices=[('HIGH', 'Alta'), ('MEDIUM', 'Media'), ('LOW', 'Baja')], max_length=20, verbose_name='Demanda de mercado')),
                ('expected_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio esperado')),
                ('estimated_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rendimiento estimado (kg/ha)')),
                ('estimated_harvest_date', models.DateField(blank=True, null=True, verbose_name='Fecha estimada de cosecha')),
                ('recommendation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planting_detail', to='ai_recommendations.airecommendation', verbose_name='Recomendación')),
                ('recommended_crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planting_recommendations', to='parcels.crop', verbose_name='Cultivo recomendado')),
            ],
            options={
                'verbose_name': 'Detalle de Recomendación de Siembra',
                'verbose_name_plural': 'Detalles de Recomendaciones de Siembra',
                'db_table': 'planting_recommendations',
            },
        ),
        migrations.AddIndex(
            model_name='airecommendation',
            index=models.Index(fields=['partner', 'recommendation_type'], name='ai_recommen_partner_557301_idx'),
        ),
        migrations.AddIndex(
            model_name='airecommendation',
            index=models.Index(fields=['parcel', 'is_active'], name='ai_recommen_parcel__93e987_idx'),
        ),
    ]
