# Generated by Django 5.0.1 on 2025-11-21 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('parcels', '0002_initial'),
        ('partners', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('harvest_date', models.DateField(verbose_name='Fecha de cosecha')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad (kg)')),
                ('quality_grade', models.CharField(blank=True, max_length=50, verbose_name='Grado de calidad')),
                ('moisture_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje de humedad')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura (°C)')),
                ('storage_location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación de almacenamiento')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvested_products', to='campaigns.campaign', verbose_name='Campaña')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvested_products', to='parcels.parcel', verbose_name='Parcela')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvested_products', to='partners.partner', verbose_name='Socio')),
            ],
            options={
                'verbose_name': 'Producto Cosechado',
                'verbose_name_plural': 'Productos Cosechados',
                'db_table': 'harvested_products',
                'ordering': ['-harvest_date'],
                'indexes': [models.Index(fields=['campaign', 'harvest_date'], name='harvested_p_campaig_0cbdaf_idx'), models.Index(fields=['parcel'], name='harvested_p_parcel__6e9a04_idx'), models.Index(fields=['partner'], name='harvested_p_partner_11853c_idx')],
            },
        ),
    ]
