# Generated by Django 5.0.1 on 2025-11-21 05:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('farm_activities', '0001_initial'),
        ('inventory', '0001_initial'),
        ('parcels', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SEEDS', 'Semillas'), ('FERTILIZERS', 'Fertilizantes'), ('PESTICIDES', 'Pesticidas'), ('LABOR', 'Mano de Obra'), ('MACHINERY', 'Maquinaria'), ('IRRIGATION', 'Riego'), ('TRANSPORT', 'Transporte'), ('OTHER', 'Otros')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Gasto',
                'verbose_name_plural': 'Categorías de Gastos',
                'db_table': 'expense_categories',
            },
        ),
        migrations.CreateModel(
            name='FieldExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('expense_date', models.DateField(verbose_name='Fecha del gasto')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo unitario')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo total')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_expenses', to='campaigns.campaign', verbose_name='Campaña')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='financial.expensecategory', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('farm_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='farm_activities.farmactivity', verbose_name='Labor relacionada')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='inventory.inventoryitem', verbose_name='Insumo relacionado')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_expenses', to='parcels.parcel', verbose_name='Parcela')),
            ],
            options={
                'verbose_name': 'Gasto de Campo',
                'verbose_name_plural': 'Gastos de Campo',
                'db_table': 'field_expenses',
                'ordering': ['-expense_date'],
                'indexes': [models.Index(fields=['parcel', 'campaign'], name='field_expen_parcel__604ce7_idx'), models.Index(fields=['expense_date'], name='field_expen_expense_3c61af_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParcelProfitability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ingresos totales')),
                ('total_production', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Producción total (kg)')),
                ('average_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio promedio')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gastos totales')),
                ('seed_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fertilizer_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pesticide_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('labor_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Utilidad bruta')),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Margen de utilidad (%)')),
                ('roi', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ROI (%)')),
                ('cost_per_hectare', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo por hectárea')),
                ('revenue_per_hectare', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ingreso por hectárea')),
                ('yield_per_hectare', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rendimiento por hectárea (kg/ha)')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Calculado el')),
                ('notes', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profitability_records', to='campaigns.campaign', verbose_name='Campaña')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profitability_records', to='parcels.parcel', verbose_name='Parcela')),
            ],
            options={
                'verbose_name': 'Rentabilidad de Parcela',
                'verbose_name_plural': 'Rentabilidad de Parcelas',
                'db_table': 'parcel_profitability',
                'ordering': ['-calculated_at'],
                'unique_together': {('parcel', 'campaign')},
            },
        ),
    ]
