# Generated by Django 4.2.26 on 2025-11-26 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={},
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldexpense',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcelprofitability',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(choices=[('SEEDS', 'Semillas'), ('FERTILIZERS', 'Fertilizantes'), ('PESTICIDES', 'Pesticidas'), ('LABOR', 'Mano de Obra'), ('MACHINERY', 'Maquinaria'), ('IRRIGATION', 'Riego'), ('TRANSPORT', 'Transporte'), ('OTHER', 'Otros')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterModelTable(
            name='expensecategory',
            table=None,
        ),
    ]
