# Generated by Django 5.0.1 on 2025-11-21 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SEED', 'Semilla'), ('PESTICIDE', 'Pesticida'), ('FERTILIZER', 'Fertilizante'), ('TOOL', 'Herramienta'), ('OTHER', 'Otro')], max_length=50, unique=True, verbose_name='Categoría')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Categoría de Inventario',
                'verbose_name_plural': 'Categorías de Inventario',
                'db_table': 'inventory_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('species', models.CharField(blank=True, max_length=200, verbose_name='Especie')),
                ('variety', models.CharField(blank=True, max_length=200, verbose_name='Variedad')),
                ('brand', models.CharField(blank=True, max_length=200, verbose_name='Marca')),
                ('germination_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje de germinación')),
                ('unit_of_measure', models.CharField(max_length=50, verbose_name='Unidad de medida')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock actual')),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock mínimo')),
                ('maximum_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Stock máximo')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio unitario')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.inventorycategory', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Item de Inventario',
                'verbose_name_plural': 'Items de Inventario',
                'db_table': 'inventory_items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('ENTRY', 'Entrada'), ('EXIT', 'Salida'), ('ADJUSTMENT', 'Ajuste')], max_length=20, verbose_name='Tipo de movimiento')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='Referencia')),
                ('reason', models.TextField(verbose_name='Motivo')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo unitario')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_movements', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'inventory_movements',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alerta')),
                ('current_stock', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock actual')),
                ('minimum_stock', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock mínimo')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resuelta')),
                ('resolved_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.inventoryitem', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Alerta de Stock',
                'verbose_name_plural': 'Alertas de Stock',
                'db_table': 'stock_alerts',
                'ordering': ['-alert_date'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['code'], name='inventory_i_code_5af0df_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['category'], name='inventory_i_categor_9c3f50_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['item', 'date'], name='inventory_m_item_id_b21046_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['movement_type'], name='inventory_m_movemen_a3c722_idx'),
        ),
    ]
