# Generated by Django 4.2.26 on 2025-11-26 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorycategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='inventory_i_code_5af0df_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='inventory_i_categor_9c3f50_idx',
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockalert',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventorycategory',
            name='name',
            field=models.CharField(choices=[('SEED', 'Semilla'), ('PESTICIDE', 'Pesticida'), ('FERTILIZER', 'Fertilizante'), ('TOOL', 'Herramienta'), ('OTHER', 'Otro')], max_length=50, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Código'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorycategory',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterModelTable(
            name='inventorycategory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='inventoryitem',
            table=None,
        ),
    ]
