# Generated by Django 5.0.1 on 2025-11-21 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PERFORMANCE', 'Rendimiento'), ('FINANCIAL', 'Financiero'), ('POPULATION', 'Población'), ('HECTARES', 'Hectáreas'), ('TRACEABILITY', 'Trazabilidad'), ('CUSTOM', 'Personalizado')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Reporte',
                'verbose_name_plural': 'Tipos de Reportes',
                'db_table': 'report_types',
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('filters', models.JSONField(default=dict, verbose_name='Filtros aplicados')),
                ('file_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='Tamaño (bytes)')),
                ('data', models.JSONField(default=dict, verbose_name='Datos del reporte')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('download_count', models.IntegerField(default=0)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_reports', to='reports.reporttype')),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'db_table': 'generated_reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
