# Generated by Django 4.2.26 on 2025-11-26 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporttype',
            options={},
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporttype',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reporttype',
            name='name',
            field=models.CharField(choices=[('PERFORMANCE', 'Rendimiento'), ('FINANCIAL', 'Financiero'), ('POPULATION', 'Población'), ('HECTARES', 'Hectáreas'), ('TRACEABILITY', 'Trazabilidad'), ('CUSTOM', 'Personalizado')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='reporttype',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterModelTable(
            name='reporttype',
            table=None,
        ),
    ]
