# Generated by Django 5.0.1 on 2025-11-21 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('partners', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SEED', 'Semillas'), ('PESTICIDE', 'Pesticidas'), ('FERTILIZER', 'Fertilizantes'), ('TECHNICAL_SUPPORT', 'Soporte Técnico'), ('TRAINING', 'Capacitación'), ('OTHER', 'Otro')], max_length=50, unique=True, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Tipo de Solicitud',
                'verbose_name_plural': 'Tipos de Solicitud',
                'db_table': 'request_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=50, unique=True, verbose_name='Número de solicitud')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción detallada')),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=20, verbose_name='Prioridad')),
                ('request_date', models.DateField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('required_date', models.DateField(blank=True, null=True, verbose_name='Fecha requerida')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_REVIEW', 'En Revisión'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('response', models.TextField(blank=True, verbose_name='Respuesta')),
                ('response_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='partners.partner', verbose_name='Socio')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_requests', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
            ],
            options={
                'verbose_name': 'Solicitud de Socio',
                'verbose_name_plural': 'Solicitudes de Socios',
                'db_table': 'partner_requests',
                'ordering': ['-request_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='request_attachments/', verbose_name='Archivo')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nombre del archivo')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de archivo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='requests.partnerrequest', verbose_name='Solicitud')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Adjunto de Solicitud',
                'verbose_name_plural': 'Adjuntos de Solicitudes',
                'db_table': 'request_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad solicitada')),
                ('approved_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad aprobada')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem', verbose_name='Item')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='requests.partnerrequest', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Item de Solicitud',
                'verbose_name_plural': 'Items de Solicitud',
                'db_table': 'request_items',
            },
        ),
        migrations.AddField(
            model_name='partnerrequest',
            name='items',
            field=models.ManyToManyField(related_name='requests', through='requests.RequestItem', to='inventory.inventoryitem', verbose_name='Items solicitados'),
        ),
        migrations.AddField(
            model_name='partnerrequest',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='requests.requesttype', verbose_name='Tipo de solicitud'),
        ),
        migrations.AddIndex(
            model_name='partnerrequest',
            index=models.Index(fields=['request_number'], name='partner_req_request_2634f6_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerrequest',
            index=models.Index(fields=['partner', 'status'], name='partner_req_partner_2b27f5_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerrequest',
            index=models.Index(fields=['status', 'priority'], name='partner_req_status_5b98aa_idx'),
        ),
    ]
