# Generated by Django 4.2.26 on 2025-11-26 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='requesttype',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='partnerrequest',
            name='partner_req_request_2634f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='partnerrequest',
            name='partner_req_partner_2b27f5_idx',
        ),
        migrations.RemoveIndex(
            model_name='partnerrequest',
            name='partner_req_status_5b98aa_idx',
        ),
        migrations.AddField(
            model_name='partnerrequest',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestattachment',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestitem',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requesttype',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partnerrequest',
            name='request_number',
            field=models.CharField(max_length=50, verbose_name='Número de solicitud'),
        ),
        migrations.AlterField(
            model_name='requesttype',
            name='name',
            field=models.CharField(choices=[('SEED', 'Semillas'), ('PESTICIDE', 'Pesticidas'), ('FERTILIZER', 'Fertilizantes'), ('TECHNICAL_SUPPORT', 'Soporte Técnico'), ('TRAINING', 'Capacitación'), ('OTHER', 'Otro')], max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterUniqueTogether(
            name='partnerrequest',
            unique_together={('organization', 'request_number')},
        ),
        migrations.AlterUniqueTogether(
            name='requesttype',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterModelTable(
            name='partnerrequest',
            table=None,
        ),
        migrations.AlterModelTable(
            name='requesttype',
            table=None,
        ),
    ]
