# Generated by Django 4.2.26 on 2025-12-08 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('partner', 'Socio'), ('parcel', 'Parcela'), ('product', 'Producto'), ('order', 'Orden'), ('campaign', 'Campaña')], max_length=20, verbose_name='Tipo de modelo')),
                ('object_id', models.IntegerField(verbose_name='ID del objeto')),
                ('qr_data', models.TextField(verbose_name='Datos del QR')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Imagen QR')),
                ('scans_count', models.IntegerField(default=0, verbose_name='Número de escaneos')),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='Último escaneo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Código QR',
                'verbose_name_plural': 'Códigos QR',
                'db_table': 'qr_codes_qrcode',
                'indexes': [models.Index(fields=['model_type', 'object_id'], name='qr_codes_qr_model_t_e4e519_idx')],
                'unique_together': {('model_type', 'object_id', 'organization')},
            },
        ),
    ]
