# Generated by Django 5.0.1 on 2025-11-21 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('FROST', 'Helada'), ('HEAVY_RAIN', 'Lluvia Intensa'), ('DROUGHT', 'Sequía'), ('STRONG_WIND', 'Viento Fuerte'), ('HAIL', 'Granizo'), ('EXTREME_HEAT', 'Calor Extremo')], max_length=20)),
                ('severity', models.CharField(choices=[('WARNING', 'Advertencia'), ('WATCH', 'Vigilancia'), ('ADVISORY', 'Aviso')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(verbose_name='Inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fin')),
                ('action_recommended', models.TextField(verbose_name='Acción recomendada')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_alerts', to='partners.community')),
            ],
            options={
                'verbose_name': 'Alerta Climática',
                'verbose_name_plural': 'Alertas Climáticas',
                'db_table': 'weather_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('forecast_date', models.DateField(verbose_name='Fecha del pronóstico')),
                ('forecast_time', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temp_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temp_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weather_condition', models.CharField(max_length=100)),
                ('precipitation_probability', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Probabilidad de lluvia (%)')),
                ('precipitation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Cantidad de lluvia (mm)')),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_source', models.CharField(default='OpenWeatherMap', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_forecasts', to='partners.community', verbose_name='Comunidad')),
            ],
            options={
                'verbose_name': 'Pronóstico del Tiempo',
                'verbose_name_plural': 'Pronósticos del Tiempo',
                'db_table': 'weather_forecasts',
                'ordering': ['forecast_date', 'forecast_time'],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitud')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura (°C)')),
                ('feels_like', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sensación térmica (°C)')),
                ('temp_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura mínima (°C)')),
                ('temp_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura máxima (°C)')),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Humedad (%)')),
                ('pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Presión (hPa)')),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Velocidad del viento (m/s)')),
                ('wind_direction', models.IntegerField(blank=True, null=True, verbose_name='Dirección del viento (°)')),
                ('precipitation', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Precipitación (mm)')),
                ('rain_probability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Probabilidad de lluvia (%)')),
                ('weather_condition', models.CharField(blank=True, max_length=100, verbose_name='Condición climática')),
                ('weather_description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('cloudiness', models.IntegerField(blank=True, null=True, verbose_name='Nubosidad (%)')),
                ('visibility', models.IntegerField(blank=True, null=True, verbose_name='Visibilidad (m)')),
                ('uv_index', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Índice UV')),
                ('data_source', models.CharField(default='OpenWeatherMap', max_length=100, verbose_name='Fuente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='partners.community', verbose_name='Comunidad')),
            ],
            options={
                'verbose_name': 'Dato Climático',
                'verbose_name_plural': 'Datos Climáticos',
                'db_table': 'weather_data',
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['community', 'date'], name='weather_dat_communi_2d1040_idx'), models.Index(fields=['date'], name='weather_dat_date_b3710c_idx')],
            },
        ),
    ]
