# Generated by Django 5.0.1 on 2025-11-21 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('parcels', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phenological_stage', models.CharField(choices=[('SEEDLING', 'Plántula'), ('VEGETATIVE', 'Vegetativo'), ('FLOWERING', 'Floración'), ('FRUITING', 'Fructificación'), ('RIPENING', 'Maduración'), ('HARVEST_READY', 'Listo para Cosecha')], max_length=20, verbose_name='Etapa fenológica')),
                ('health_status', models.CharField(choices=[('EXCELLENT', 'Excelente'), ('GOOD', 'Bueno'), ('FAIR', 'Regular'), ('POOR', 'Malo'), ('CRITICAL', 'Crítico')], max_length=20, verbose_name='Estado de salud')),
                ('plant_height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura de planta (cm)')),
                ('leaf_color_index', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Índice de color de hoja')),
                ('soil_moisture', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Humedad del suelo (%)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura (°C)')),
                ('pest_presence', models.BooleanField(default=False, verbose_name='Presencia de plagas')),
                ('disease_presence', models.BooleanField(default=False, verbose_name='Presencia de enfermedades')),
                ('pest_details', models.TextField(blank=True, verbose_name='Detalles de plagas')),
                ('disease_details', models.TextField(blank=True, verbose_name='Detalles de enfermedades')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recomendaciones')),
                ('images', models.JSONField(default=list, verbose_name='Imágenes')),
                ('monitoring_date', models.DateField(verbose_name='Fecha de monitoreo')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_records', to='campaigns.campaign', verbose_name='Campaña')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_records', to='parcels.parcel', verbose_name='Parcela')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_records', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Monitoreo de Cultivo',
                'verbose_name_plural': 'Monitoreos de Cultivos',
                'db_table': 'crop_monitoring',
                'ordering': ['-monitoring_date'],
            },
        ),
        migrations.CreateModel(
            name='CropAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('PEST', 'Plaga'), ('DISEASE', 'Enfermedad'), ('WATER_STRESS', 'Estrés Hídrico'), ('NUTRIENT_DEFICIENCY', 'Deficiencia Nutricional'), ('WEATHER', 'Clima'), ('OTHER', 'Otro')], max_length=30, verbose_name='Tipo de alerta')),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], max_length=20, verbose_name='Severidad')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelta el')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notas de resolución')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.cropmonitoring', verbose_name='Monitoreo')),
            ],
            options={
                'verbose_name': 'Alerta de Cultivo',
                'verbose_name_plural': 'Alertas de Cultivos',
                'db_table': 'crop_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cropmonitoring',
            index=models.Index(fields=['parcel', 'monitoring_date'], name='crop_monito_parcel__8960ed_idx'),
        ),
        migrations.AddIndex(
            model_name='cropmonitoring',
            index=models.Index(fields=['campaign', 'health_status'], name='crop_monito_campaig_f6630c_idx'),
        ),
    ]
