# Generated by Django 5.0.1 on 2025-11-21 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0002_initial'),
        ('partners', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código de campaña')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin estimada')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin real')),
                ('target_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área objetivo (ha)')),
                ('target_production', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Producción objetivo (kg)')),
                ('status', models.CharField(choices=[('PLANNING', 'En Planificación'), ('ACTIVE', 'Activa'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PLANNING', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('parcels', models.ManyToManyField(related_name='campaigns', to='parcels.parcel', verbose_name='Parcelas asignadas')),
                ('partners', models.ManyToManyField(related_name='campaigns', to='partners.partner', verbose_name='Socios participantes')),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'db_table': 'campaigns',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['code'], name='campaigns_code_b1b082_idx'), models.Index(fields=['status'], name='campaigns_status_a03570_idx'), models.Index(fields=['start_date'], name='campaigns_start_d_5c2c6b_idx')],
            },
        ),
    ]
