# Generated by Django 4.2.26 on 2025-11-26 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='campaign',
            name='campaigns_code_b1b082_idx',
        ),
        migrations.RemoveIndex(
            model_name='campaign',
            name='campaigns_status_a03570_idx',
        ),
        migrations.RemoveIndex(
            model_name='campaign',
            name='campaigns_start_d_5c2c6b_idx',
        ),
        migrations.AddField(
            model_name='campaign',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Código de campaña'),
        ),
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterModelTable(
            name='campaign',
            table=None,
        ),
    ]
