# Generated by Django 5.0.1 on 2025-11-21 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('parcels', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SOWING', 'Siembra'), ('IRRIGATION', 'Riego'), ('FERTILIZATION', 'Fertilización'), ('PEST_CONTROL', 'Control de Plagas'), ('HARVEST', 'Cosecha'), ('OTHER', 'Otra')], max_length=50, unique=True, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Tipo de Labor',
                'verbose_name_plural': 'Tipos de Labores',
                'db_table': 'activity_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FarmActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='Fecha programada')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='Fecha real')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad (kg/l)')),
                ('area_covered', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área cubierta (ha)')),
                ('workers_count', models.IntegerField(default=1, verbose_name='Número de trabajadores')),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Horas trabajadas')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('weather_conditions', models.CharField(blank=True, max_length=200, verbose_name='Condiciones climáticas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='farm_activities.activitytype', verbose_name='Tipo de labor')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='campaigns.campaign', verbose_name='Campaña')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_activities', to=settings.AUTH_USER_MODEL, verbose_name='Completado por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='parcels.parcel', verbose_name='Parcela')),
            ],
            options={
                'verbose_name': 'Labor Agrícola',
                'verbose_name_plural': 'Labores Agrícolas',
                'db_table': 'farm_activities',
                'ordering': ['-scheduled_date'],
                'indexes': [models.Index(fields=['campaign', 'scheduled_date'], name='farm_activi_campaig_83756a_idx'), models.Index(fields=['parcel', 'activity_type'], name='farm_activi_parcel__3dc022_idx'), models.Index(fields=['status'], name='farm_activi_status_36c406_idx')],
            },
        ),
    ]
