# Generated by Django 4.2.26 on 2025-11-26 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('farm_activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitytype',
            options={},
        ),
        migrations.AddField(
            model_name='activitytype',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmactivity',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='name',
            field=models.CharField(choices=[('SOWING', 'Siembra'), ('IRRIGATION', 'Riego'), ('FERTILIZATION', 'Fertilización'), ('PEST_CONTROL', 'Control de Plagas'), ('HARVEST', 'Cosecha'), ('OTHER', 'Otra')], max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterUniqueTogether(
            name='activitytype',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterModelTable(
            name='activitytype',
            table=None,
        ),
    ]
