# Generated by Django 5.0.1 on 2025-11-21 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0002_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(max_length=50, unique=True, verbose_name='Número de envío')),
                ('destination_address', models.TextField(verbose_name='Dirección de entrega')),
                ('scheduled_date', models.DateField(verbose_name='Fecha programada')),
                ('actual_delivery_date', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega real')),
                ('carrier', models.CharField(blank=True, max_length=200, verbose_name='Transportista')),
                ('vehicle_plate', models.CharField(blank=True, max_length=20, verbose_name='Placa del vehículo')),
                ('driver_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del conductor')),
                ('driver_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del conductor')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SCHEDULED', 'Programado'), ('IN_TRANSIT', 'En Tránsito'), ('DELIVERED', 'Entregado'), ('FAILED', 'Fallido'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('tracking_number', models.CharField(blank=True, max_length=200, verbose_name='Número de seguimiento')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('received_by', models.CharField(blank=True, max_length=200, verbose_name='Recibido por')),
                ('signature', models.TextField(blank=True, verbose_name='Firma (base64)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipments', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('destination_community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='partners.community', verbose_name='Comunidad destino')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='sales.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'db_table': 'shipments',
                'ordering': ['-scheduled_date', '-created_at'],
                'indexes': [models.Index(fields=['shipment_number'], name='shipments_shipmen_67925e_idx'), models.Index(fields=['order', 'status'], name='shipments_order_i_1ac412_idx'), models.Index(fields=['scheduled_date'], name='shipments_schedul_287184_idx')],
            },
        ),
    ]
