# Generated by Django 4.2.26 on 2025-11-26 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='shipment',
            name='shipments_shipmen_67925e_idx',
        ),
        migrations.RemoveIndex(
            model_name='shipment',
            name='shipments_order_i_1ac412_idx',
        ),
        migrations.RemoveIndex(
            model_name='shipment',
            name='shipments_schedul_287184_idx',
        ),
        migrations.AddField(
            model_name='shipment',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_number',
            field=models.CharField(max_length=50, verbose_name='Número de envío'),
        ),
        migrations.AlterUniqueTogether(
            name='shipment',
            unique_together={('organization', 'shipment_number')},
        ),
        migrations.AlterModelTable(
            name='shipment',
            table=None,
        ),
    ]
