# Generated by Django 4.2.26 on 2025-12-08 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('alerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Email habilitado')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Push habilitado')),
                ('notify_sales', models.BooleanField(default=True, verbose_name='Notificar ventas')),
                ('notify_payments', models.BooleanField(default=True, verbose_name='Notificar pagos')),
                ('notify_stock', models.BooleanField(default=True, verbose_name='Notificar stock')),
                ('notify_requests', models.BooleanField(default=True, verbose_name='Notificar solicitudes')),
                ('notify_alerts', models.BooleanField(default=True, verbose_name='Notificar alertas')),
                ('notify_tasks', models.BooleanField(default=True, verbose_name='Notificar tareas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Preferencia de notificación',
                'verbose_name_plural': 'Preferencias de notificación',
                'db_table': 'notifications_preference',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('type', models.CharField(choices=[('INFO', 'Información'), ('SUCCESS', 'Éxito'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('SALE', 'Venta'), ('PAYMENT', 'Pago'), ('STOCK', 'Inventario'), ('REQUEST', 'Solicitud'), ('ALERT', 'Alerta'), ('TASK', 'Tarea')], default='INFO', max_length=20, verbose_name='Tipo')),
                ('read', models.BooleanField(default=False, verbose_name='Leída')),
                ('extra_data', models.JSONField(blank=True, help_text='Información adicional en formato JSON', null=True, verbose_name='Datos adicionales')),
                ('action_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL de acción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerts.alert', verbose_name='Alerta relacionada')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.organization', verbose_name='Organización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read', '-created_at'], name='notificatio_user_id_4fcc58_idx'), models.Index(fields=['type', '-created_at'], name='notificatio_type_36f2e6_idx')],
            },
        ),
    ]
